import { StyleSheet } from 'react-native';

export const mobileFooterStyles = StyleSheet.create({
  container: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 8,
  },
  button: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  paddingVertical: 4,
  },
  activeButton: {
    backgroundColor: '#2F4F4F',
  borderRadius: 10,
  paddingVertical: 8,
  },
  iconLabel: {
  fontSize: 11,
  marginTop: 3,
    color: '#2F4F4F',
    fontWeight: '500',
  },
  activeLabel: {
    color: '#ffffff',
  },
  cartBadgeContainer: {
    position: 'absolute',
    top: 4,
  right: 22,
    backgroundColor: '#FF4D4F',
    borderRadius: 9,
    minWidth: 18,
    paddingHorizontal: 4,
    paddingVertical: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
});