import { StyleSheet } from 'react-native';

export const createShoppingCartStyles = (isDesktop: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f8f9fa',
      alignItems: isDesktop ? 'center' : 'stretch',
      paddingHorizontal: isDesktop ? 24 : 0,
    },
    cartTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      maxWidth: isDesktop ? 1100 : undefined,
      alignSelf: 'center',
      paddingHorizontal: isDesktop ? 32 : 16,
      paddingTop: isDesktop ? 28 : 20,
      paddingBottom: isDesktop ? 12 : 8,
      marginBottom: isDesktop ? 12 : 8,
    },
    cartTitle: {
      fontSize: isDesktop ? 26 : 20,
      fontWeight: '700',
      color: '#333',
    },
    clearAllButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: '#dc3545',
      backgroundColor: '#fff',
    },
    clearAllButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#dc3545',
      marginLeft: 6,
    },
    cartList: {
      paddingHorizontal: isDesktop ? 32 : 16,
      paddingVertical: isDesktop ? 16 : 12,
      paddingBottom: isDesktop ? 24 : 16,
      width: '100%',
      maxWidth: isDesktop ? 1100 : undefined,
      alignSelf: 'center',
    },
    cartItem: {
      flexDirection: isDesktop ? 'row' : 'column',
      backgroundColor: 'white',
      borderRadius: 12,
      padding: isDesktop ? 24 : 16,
      marginBottom: 16,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      alignItems: isDesktop ? 'center' : 'flex-start',
    },
    productImage: {
      width: isDesktop ? 90 : 70,
      height: isDesktop ? 90 : 70,
      borderRadius: 10,
      marginRight: isDesktop ? 16 : 0,
      alignSelf: isDesktop ? 'flex-start' : 'center',
    },
    itemDetails: {
      flex: 1,
      width: '100%',
    },
    productName: {
      fontSize: isDesktop ? 18 : 16,
      fontWeight: '600',
      color: '#333',
      marginBottom: 4,
    },
    supplierText: {
      fontSize: 13,
      color: '#007bff',
      fontWeight: '500',
      marginBottom: 4,
    },
    loteInfo: {
      fontSize: 13,
      color: '#666',
      marginBottom: 4,
    },
    priceText: {
      fontSize: 15,
      color: '#28a745',
      fontWeight: '600',
    },
    outOfStockText: {
      fontSize: 12,
      color: '#dc3545',
      fontWeight: '600',
      marginTop: 6,
    },
    quantityControls: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: isDesktop ? 24 : 12,
      marginTop: isDesktop ? 0 : 12,
      alignSelf: isDesktop ? 'center' : 'flex-start',
    },
    quantityButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: '#f8f9fa',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#dee2e6',
    },
    quantityText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
      marginHorizontal: 14,
      minWidth: 28,
      textAlign: 'center',
    },
    itemActions: {
      alignItems: isDesktop ? 'flex-end' : 'flex-start',
      marginTop: isDesktop ? 0 : 12,
      width: isDesktop ? undefined : '100%',
    },
    itemTotal: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#28a745',
      marginBottom: 8,
    },
    removeButton: {
      padding: 6,
      alignSelf: isDesktop ? 'flex-end' : 'flex-start',
    },
    cartSummary: {
      backgroundColor: 'white',
      padding: isDesktop ? 28 : 20,
      marginHorizontal: isDesktop ? 0 : 16,
      marginBottom: isDesktop ? 32 : 20,
      marginTop: isDesktop ? 8 : 4,
      borderRadius: 12,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      width: '100%',
      maxWidth: isDesktop ? 500 : undefined,
      alignSelf: 'center',
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    summaryLabel: {
      fontSize: 16,
      color: '#666',
    },
    summaryValue: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
    },
    summaryTotal: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#28a745',
    },
    checkoutButton: {
      backgroundColor: '#28a745',
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 16,
    },
    disabledButton: {
      backgroundColor: '#6c757d',
      opacity: 0.6,
    },
    checkoutButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: 'bold',
    },
    emptyCart: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: isDesktop ? 60 : 40,
    },
    emptyCartText: {
      fontSize: 20,
      fontWeight: '600',
      color: '#666',
      marginTop: 16,
      marginBottom: 8,
      textAlign: 'center',
    },
    emptyCartSubtext: {
      fontSize: 15,
      color: '#999',
      textAlign: 'center',
      marginBottom: 24,
    },
    continueShoppingButton: {
      backgroundColor: '#007bff',
      paddingHorizontal: 28,
      paddingVertical: 12,
      borderRadius: 8,
    },
    continueShoppingText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 16,
    },
    modalContent: {
      backgroundColor: 'white',
      borderRadius: 12,
      padding: 24,
      width: '100%',
      maxWidth: isDesktop ? 460 : 400,
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#333',
      textAlign: 'center',
      marginBottom: 18,
    },
    modalMessage: {
      fontSize: 16,
      color: '#666',
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 22,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    modalButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      flex: 1,
      marginHorizontal: 5,
    },
    cancelButton: {
      backgroundColor: '#6c757d',
    },
    confirmButton: {
      backgroundColor: '#dc3545',
    },
    destructiveButton: {
      backgroundColor: '#dc3545',
    },
    cancelButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    confirmButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    destructiveButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
  });