import { StyleSheet } from "react-native";

export const createPromotionDetailStyles = (isDesktop: boolean) => {
  const maxContentWidth = isDesktop ? 1080 : undefined;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      paddingHorizontal: isDesktop ? 24 : 0,
    },
    container: {
      flexGrow: 1,
      width: '100%',
      paddingHorizontal: isDesktop ? 32 : 16,
      paddingVertical: isDesktop ? 24 : 12,
      alignItems: 'center',
      backgroundColor: '#fff',
    },
    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    errorText: { color: 'red', fontSize: 16, textAlign: 'center', marginBottom: 10 },
    retryText: { color: '#007bff', fontSize: 16, marginTop: 10 },
    header: {
      width: '100%',
      maxWidth: maxContentWidth,
      paddingHorizontal: isDesktop ? 32 : 12,
      marginBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
      paddingBottom: 18,
      alignSelf: 'center',
    },
    promotionTitle: {
      fontSize: isDesktop ? 28 : 22,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 6,
      textAlign: 'center',
    },
    supplierName: { fontSize: isDesktop ? 18 : 16, color: 'grey', textAlign: 'center', marginBottom: 6 },
    dateInfo: { fontSize: isDesktop ? 16 : 14, color: 'grey', textAlign: 'center', marginBottom: 10 },
    productItem: {
      flexDirection: isDesktop ? 'row' : 'column',
      alignItems: isDesktop ? 'center' : 'flex-start',
      width: '100%',
      maxWidth: maxContentWidth,
      backgroundColor: '#fff',
      borderRadius: 12,
      paddingHorizontal: isDesktop ? 28 : 16,
      paddingVertical: isDesktop ? 20 : 14,
      marginBottom: 16,
      elevation: isDesktop ? 3 : 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDesktop ? 0.1 : 0,
      shadowRadius: isDesktop ? 6 : 0,
      borderWidth: isDesktop ? 0 : 1,
      borderColor: isDesktop ? 'transparent' : '#f0f0f0',
    },
    productImage: {
      width: isDesktop ? 120 : 90,
      height: isDesktop ? 120 : 90,
      borderRadius: 10,
      marginRight: isDesktop ? 24 : 0,
      marginBottom: isDesktop ? 0 : 12,
      backgroundColor: '#f0f0f0',
      alignSelf: isDesktop ? 'flex-start' : 'center',
    },
    productInfo: {
      flex: 1,
      justifyContent: 'center',
      marginRight: isDesktop ? 20 : 0,
      width: '100%',
    },
    productName: { fontSize: isDesktop ? 18 : 16, fontWeight: '600', color: '#444', marginBottom: 6 },
    productMeasure: { fontSize: isDesktop ? 14 : 13, color: 'grey', marginBottom: 4 },
    originalPrice: { fontSize: 12, textDecorationLine: 'line-through', color: '#aaa', marginBottom: 2 },
    promoPrice: { fontSize: isDesktop ? 18 : 16, fontWeight: 'bold', color: '#28a745', marginBottom: 6 },
    productStock: { fontSize: 13, color: '#555', marginBottom: 4 },
    productValidity: { fontSize: 13, color: '#555' },
    addToCartButton: {
      flexDirection: 'row',
      backgroundColor: '#007bff',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: isDesktop ? 140 : 120,
      alignSelf: isDesktop ? 'center' : 'stretch',
      marginTop: isDesktop ? 0 : 12,
    },
    addToCartButtonText: { color: 'white', fontSize: 14, fontWeight: 'bold', marginLeft: 6 },
    disabledButton: { backgroundColor: '#ced4da' },
    emptyText: { textAlign: 'center', marginTop: 50, fontSize: 16, color: 'grey' },

    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: isDesktop ? 24 : 12,
    },
    modalContent: {
      backgroundColor: 'white',
      borderRadius: 12,
      paddingVertical: isDesktop ? 28 : 20,
      paddingHorizontal: isDesktop ? 28 : 18,
      width: isDesktop ? '60%' : '86%',
      maxWidth: isDesktop ? 520 : 340,
      alignSelf: 'center',
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#333',
      textAlign: 'center',
      marginBottom: 20,
    },
    modalProductInfo: {
      flexDirection: isDesktop ? 'row' : 'column',
      alignItems: isDesktop ? 'center' : 'flex-start',
      marginBottom: 18,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
    },
    modalProductImage: {
      width: isDesktop ? 80 : 64,
      height: isDesktop ? 80 : 64,
      borderRadius: 10,
      marginRight: isDesktop ? 18 : 0,
      marginBottom: isDesktop ? 0 : 12,
      backgroundColor: '#f0f0f0',
      alignSelf: isDesktop ? 'flex-start' : 'center',
    },
    modalProductDetails: {
      flex: 1,
      width: '100%',
    },
    modalProductName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
      marginBottom: 4,
    },
    modalProductPrice: {
      fontSize: 14,
      color: '#28a745',
      fontWeight: '500',
      marginBottom: 2,
    },
    modalProductStock: { fontSize: 13, color: '#666' },
    quantitySelector: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
    },
    quantityButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#f8f9fa',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#dee2e6',
    },
    quantityInput: {
      marginHorizontal: 14,
      minWidth: 70,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#ced4da',
      textAlign: 'center',
      fontSize: 18,
      fontWeight: '600',
      color: '#333',
      backgroundColor: '#f8f9fa',
    },
    totalText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#28a745',
      textAlign: 'center',
      marginBottom: 20,
    },
    modalButtons: {
      flexDirection: isDesktop ? 'row' : 'column',
      justifyContent: 'space-between',
      alignItems: 'stretch',
    },
    modalButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      flex: isDesktop ? 1 : undefined,
      marginHorizontal: isDesktop ? 5 : 0,
      marginVertical: isDesktop ? 0 : 6,
      width: isDesktop ? undefined : '100%',
    },
    cancelButton: {
      backgroundColor: '#6c757d',
    },
    confirmButton: {
      backgroundColor: '#28a745',
    },
    cancelButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    confirmButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 8,
    },
  });
};