import { StyleSheet } from "react-native";

export const createPromotionDetailStyles = (isDesktop: boolean) => {
  const maxContentWidth = isDesktop ? 1080 : undefined;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: '#f4f5f7',
      alignItems: 'center',
      paddingHorizontal: isDesktop ? 24 : 0,
    },
    container: {
      flexGrow: 1,
      width: '100%',
      paddingHorizontal: isDesktop ? 32 : 16,
      paddingVertical: isDesktop ? 24 : 12,
      alignItems: 'center',
      backgroundColor: '#f4f5f7',
    },
    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    errorText: { color: 'red', fontSize: 16, textAlign: 'center', marginBottom: 10 },
    retryText: { color: '#007bff', fontSize: 16, marginTop: 10 },
    header: {
      width: '100%',
      maxWidth: maxContentWidth,
      paddingHorizontal: isDesktop ? 32 : 12,
      marginBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
      paddingBottom: 18,
      alignSelf: 'center',
    },
    promotionTitle: {
      fontSize: isDesktop ? 28 : 22,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 6,
      textAlign: 'center',
    },
    supplierName: { fontSize: isDesktop ? 18 : 16, color: 'grey', textAlign: 'center', marginBottom: 6 },
    dateInfo: { fontSize: isDesktop ? 16 : 14, color: 'grey', textAlign: 'center', marginBottom: 10 },
    productItem: {
      width: '100%',
      maxWidth: maxContentWidth,
      backgroundColor: '#fff',
      borderRadius: 14,
      paddingHorizontal: isDesktop ? 28 : 18,
      paddingVertical: isDesktop ? 22 : 18,
      marginBottom: 16,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      borderWidth: isDesktop ? 0 : 1,
      borderColor: '#ececec',
      alignSelf: 'center',
    },
    productHeaderRow: {
      flexDirection: isDesktop ? 'row' : 'column',
      alignItems: isDesktop ? 'flex-start' : 'center',
      width: '100%',
      marginBottom: isDesktop ? 12 : 16,
    },
    productImage: {
      width: isDesktop ? 120 : 90,
      height: isDesktop ? 120 : 90,
      borderRadius: 10,
      marginRight: isDesktop ? 18 : 0,
      marginBottom: isDesktop ? 0 : 12,
      backgroundColor: '#f0f0f0',
      alignSelf: isDesktop ? 'flex-start' : 'center',
    },
    productInfo: {
      flex: 1,
      justifyContent: 'center',
      marginRight: isDesktop ? 20 : 0,
      width: '100%',
      alignItems: isDesktop ? 'flex-start' : 'center',
    },
    productName: {
      fontSize: isDesktop ? 18 : 16,
      fontWeight: '600',
      color: '#444',
      marginBottom: 6,
      textAlign: isDesktop ? 'left' : 'center',
    },
    productMeasure: {
      fontSize: isDesktop ? 14 : 13,
      color: 'grey',
      marginBottom: 4,
      textAlign: isDesktop ? 'left' : 'center',
    },
    infoChipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 6,
      justifyContent: isDesktop ? 'flex-start' : 'center',
    },
    infoChip: {
      backgroundColor: '#eef2ff',
      color: '#334155',
      fontSize: 12,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      marginRight: 6,
      marginBottom: 6,
      fontWeight: '500',
    },
    originalPrice: { fontSize: 12, textDecorationLine: 'line-through', color: '#aaa', marginBottom: 2, textAlign: isDesktop ? 'left' : 'center' },
    promoPrice: { fontSize: isDesktop ? 22 : 18, fontWeight: 'bold', color: '#28a745', textAlign: isDesktop ? 'left' : 'center' },
    productStatsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: 6,
      marginBottom: 12,
    },
    statBubble: {
      backgroundColor: '#f8f9fa',
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: '#e4e6eb',
      marginBottom: 10,
      width: isDesktop ? '23%' : '48%',
      minWidth: isDesktop ? 180 : 150,
    },
    statLabel: {
      fontSize: 12,
      color: '#6c757d',
      marginBottom: 4,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    statValue: {
      fontSize: 16,
      fontWeight: '600',
      color: '#212529',
    },
    productFooterRow: {
      flexDirection: isDesktop ? 'row' : 'column',
      alignItems: isDesktop ? 'center' : 'flex-start',
      justifyContent: 'space-between',
      width: '100%',
      marginTop: 4,
    },
    priceGroup: {
      marginBottom: isDesktop ? 0 : 12,
      width: isDesktop ? 'auto' : '100%',
    },
    priceLabel: {
      fontSize: 13,
      color: '#6c757d',
      marginBottom: 4,
      textAlign: isDesktop ? 'left' : 'center',
    },
    addToCartButton: {
      flexDirection: 'row',
      backgroundColor: '#007bff',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: isDesktop ? 160 : undefined,
      width: isDesktop ? undefined : '100%',
      alignSelf: isDesktop ? 'center' : 'stretch',
      marginTop: isDesktop ? 0 : 8,
    },
    addToCartButtonText: { color: 'white', fontSize: 14, fontWeight: 'bold', marginLeft: 6 },
    disabledButton: { backgroundColor: '#ced4da' },
    emptyText: { textAlign: 'center', marginTop: 50, fontSize: 16, color: 'grey' },

    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: isDesktop ? 24 : 12,
    },
    modalContent: {
      backgroundColor: 'white',
      borderRadius: 12,
      paddingVertical: isDesktop ? 28 : 20,
      paddingHorizontal: isDesktop ? 28 : 18,
      width: isDesktop ? '60%' : '86%',
      maxWidth: isDesktop ? 520 : 340,
      alignSelf: 'center',
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#333',
      textAlign: 'center',
      marginBottom: 20,
    },
    modalProductInfo: {
      flexDirection: isDesktop ? 'row' : 'column',
      alignItems: isDesktop ? 'center' : 'flex-start',
      marginBottom: 18,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
    },
    modalProductImage: {
      width: isDesktop ? 80 : 64,
      height: isDesktop ? 80 : 64,
      borderRadius: 10,
      marginRight: isDesktop ? 18 : 0,
      marginBottom: isDesktop ? 0 : 12,
      backgroundColor: '#f0f0f0',
      alignSelf: isDesktop ? 'flex-start' : 'center',
    },
    modalProductDetails: {
      flex: 1,
      width: '100%',
    },
    modalProductName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
      marginBottom: 4,
    },
    modalProductPrice: {
      fontSize: 14,
      color: '#28a745',
      fontWeight: '500',
      marginBottom: 2,
    },
    modalProductStock: { fontSize: 13, color: '#666' },
    quantitySelector: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
    },
    quantityButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#f8f9fa',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#dee2e6',
    },
    quantityInput: {
      marginHorizontal: 14,
      minWidth: 70,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#ced4da',
      textAlign: 'center',
      fontSize: 18,
      fontWeight: '600',
      color: '#333',
      backgroundColor: '#f8f9fa',
    },
    totalText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#28a745',
      textAlign: 'center',
      marginBottom: 20,
    },
    modalButtons: {
      flexDirection: isDesktop ? 'row' : 'column',
      justifyContent: 'space-between',
      alignItems: 'stretch',
    },
    modalButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      flex: isDesktop ? 1 : undefined,
      marginHorizontal: isDesktop ? 5 : 0,
      marginVertical: isDesktop ? 0 : 6,
      width: isDesktop ? undefined : '100%',
    },
    cancelButton: {
      backgroundColor: '#6c757d',
    },
    confirmButton: {
      backgroundColor: '#28a745',
    },
    cancelButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    confirmButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 8,
    },
  });
};