import { StyleSheet } from "react-native";

export const promotionFormStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#212529",
    textAlign: "center",
  },
  formGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 8,
    color: "#495057",
  },
  subLabel: {
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 8,
    color: "#6c757d",
  },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
    padding: 12,
    fontSize: 16,
  },
  disabledInput: {
    backgroundColor: "#e9ecef",
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
    padding: 12,
  },
  disabledText: {
    color: "#6c757d",
    fontSize: 16,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
    backgroundColor: "#fff",
    marginBottom: 5,
  },
  picker: {
    height: 50,
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    backgroundColor: "#f8f9fa",
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
  },
  loadingText: {
    marginLeft: 10,
    color: "#6c757d",
    fontSize: 14,
  },
  inputError: {
    borderColor: "#dc3545",
  },
  errorText: {
    color: "#dc3545",
    fontSize: 12,
    marginTop: 4,
  },
  infoText: {
    color: "#6c757d",
    fontSize: 14,
    fontStyle: "italic",
    marginTop: 8,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
    padding: 12,
    fontSize: 16,
  },
  searchButton: {
    backgroundColor: "#007bff",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 4,
    marginLeft: 8,
    justifyContent: "center",
    minWidth: 80,
  },
  searchButtonText: {
    color: "#fff",
    fontWeight: "500",
    textAlign: "center",
  },
  resultsContainer: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
    backgroundColor: "#fff",
  },
  resultsList: {
    maxHeight: 200,
  },
  resultItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e9ecef",
  },
  resultItemText: {
    fontSize: 14,
    color: "#212529",
  },
  produtoInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  produtoImagem: {
    width: 40,
    height: 40,
    borderRadius: 4,
    marginRight: 8,
  },
  loadingMore: {
    padding: 8,
  },
  paginationInfo: {
    textAlign: "center",
    fontSize: 12,
    color: "#6c757d",
    padding: 4,
    borderTopWidth: 1,
    borderTopColor: "#e9ecef",
  },
  selectedItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#e9f7ef",
    borderColor: "#d1e7dd",
    borderWidth: 1,
    borderRadius: 4,
    padding: 12,
  },
  selectedItemText: {
    fontSize: 16,
    color: "#0f5132",
  },
  removeButton: {
    padding: 4,
  },
  dateContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dateField: {
    width: "48%",
  },
  dateLabel: {
    fontSize: 14,
    color: "#495057",
    marginBottom: 4,
  },
  dateInput: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
    padding: 12,
  },
  itensList: {
    marginTop: 16,
  },
  itemCard: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dee2e6",
    borderRadius: 4,
    padding: 12,
    marginBottom: 8,
  },
  itemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: "#212529",
    flex: 1,
  },
  itemActions: {
    flexDirection: "row",
  },
  itemAction: {
    padding: 4,
    marginLeft: 8,
  },
  itemDetails: {
    borderTopWidth: 1,
    borderTopColor: "#f8f9fa",
    paddingTop: 8,
  },
  itemDetail: {
    fontSize: 14,
    color: "#495057",
    marginBottom: 4,
  },
  itemDetailSmall: {
    fontSize: 12,
    color: "#6c757d",
    marginTop: 2,
  },
  submitButton: {
    backgroundColor: "#28a745",
    padding: 16,
    borderRadius: 4,
    alignItems: "center",
    marginTop: 16,
  },
  buttonDisabled: {
    backgroundColor: "#6c757d",
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "500",
  },
  cancelButton: {
    backgroundColor: "#6c757d",
    padding: 16,
    borderRadius: 4,
    alignItems: "center",
    marginTop: 16,
  },
  cancelButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "500",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 20,
    width: "90%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 16,
    textAlign: "center",
    color: "#212529",
  },
  modalProdutoInfo: {
    alignItems: "center",
    marginBottom: 16,
  },
  modalProdutoImagem: {
    width: 80,
    height: 80,
    borderRadius: 4,
    marginBottom: 8,
  },
  modalProdutoNome: {
    fontSize: 16,
    fontWeight: "500",
    textAlign: "center",
  },
  modalForm: {
    marginBottom: 16,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 4,
    color: "#495057",
  },
  modalInput: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
    padding: 12,
    fontSize: 16,
    marginBottom: 12,
  },
  loteSelector: {
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
  },
  loteList: {
    maxHeight: 120,
  },
  loteItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e9ecef",
  },
  loteSelecionado: {
    backgroundColor: "#e9f7ef",
  },
  loteItemText: {
    fontSize: 14,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 4,
    alignItems: "center",
  },
  modalCancelButton: {
    backgroundColor: "#6c757d",
    marginRight: 8,
  },
  modalConfirmButton: {
    backgroundColor: "#28a745",
    marginLeft: 8,
  },
  modalButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
  batchModeToggle: {
    flexDirection: "row",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#ced4da",
    borderRadius: 4,
    overflow: "hidden",
  },
  batchModeButton: {
    flex: 1,
    padding: 10,
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  batchModeButtonActive: {
    backgroundColor: "#007bff",
  },
  batchModeButtonText: {
    color: "#495057",
    fontWeight: "500",
  },
  batchModeButtonTextActive: {
    color: "#fff",
  },
  createBatchButton: {
    backgroundColor: "#007bff",
    padding: 12,
    borderRadius: 4,
    alignItems: "center",
    marginTop: 12,
  },
  createBatchButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
})