import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const isDesktop = width >= 960;
const maxContentWidth = isDesktop ? 1080 : width - 24;

export const promotionDetailStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingHorizontal: isDesktop ? 32 : 16,
    paddingBottom: isDesktop ? 40 : 24,
    paddingTop: isDesktop ? 24 : 12,
    backgroundColor: '#f4f5f7',
    alignItems: 'center',
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  errorText: {
    color: '#c53030',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 12,
  },
  retryText: {
    color: '#0d6efd',
    fontSize: 16,
    marginTop: 6,
  },
  header: {
    width: '100%',
    maxWidth: maxContentWidth,
    paddingHorizontal: isDesktop ? 32 : 12,
    paddingBottom: 18,
    marginBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
    alignSelf: 'center',
  },
  promotionTitle: {
    fontSize: isDesktop ? 28 : 22,
    fontWeight: '700',
    color: '#212529',
    textAlign: 'center',
    marginBottom: 6,
  },
  supplierName: {
    fontSize: isDesktop ? 18 : 16,
    color: '#6c757d',
    textAlign: 'center',
    marginBottom: 4,
  },
  dateInfo: {
    fontSize: isDesktop ? 16 : 14,
    color: '#6c757d',
    textAlign: 'center',
  },
  productItem: {
    width: '100%',
    maxWidth: maxContentWidth,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: isDesktop ? 28 : 18,
    paddingVertical: isDesktop ? 24 : 18,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: isDesktop ? 0 : 1,
    borderColor: '#edf2f7',
  },
  productHeaderRow: {
    flexDirection: isDesktop ? 'row' : 'column',
    alignItems: isDesktop ? 'flex-start' : 'center',
    width: '100%',
    marginBottom: isDesktop ? 16 : 18,
  },
  productImage: {
    width: isDesktop ? 120 : 90,
    height: isDesktop ? 120 : 90,
    borderRadius: 12,
    marginRight: isDesktop ? 20 : 0,
    marginBottom: isDesktop ? 0 : 12,
    backgroundColor: '#f1f3f5',
    alignSelf: isDesktop ? 'flex-start' : 'center',
  },
  productInfo: {
    flex: 1,
    alignItems: isDesktop ? 'flex-start' : 'center',
  },
  productName: {
    fontSize: isDesktop ? 18 : 16,
    fontWeight: '600',
    color: '#212529',
    textAlign: isDesktop ? 'left' : 'center',
    marginBottom: 6,
  },
  productMeasure: {
    fontSize: isDesktop ? 14 : 13,
    color: '#6c757d',
    textAlign: isDesktop ? 'left' : 'center',
    marginBottom: 6,
  },
  infoChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: isDesktop ? 'flex-start' : 'center',
    marginBottom: 8,
  },
  infoChip: {
    backgroundColor: '#eef2ff',
    color: '#334155',
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginRight: 6,
    marginBottom: 6,
    fontWeight: '500',
  },
  originalPrice: {
    fontSize: 12,
    textDecorationLine: 'line-through',
    color: '#adb5bd',
    textAlign: isDesktop ? 'left' : 'center',
    marginBottom: 4,
  },
  promoPrice: {
    fontSize: isDesktop ? 22 : 18,
    fontWeight: '700',
    color: '#198754',
    textAlign: isDesktop ? 'left' : 'center',
  },
  productStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 16,
  },
  statBubble: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#e9ecef',
    minWidth: isDesktop ? 190 : 150,
    flexGrow: 1,
  },
  statLabel: {
    fontSize: 12,
    color: '#6c757d',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
  },
  productFooterRow: {
    flexDirection: isDesktop ? 'row' : 'column',
    alignItems: isDesktop ? 'center' : 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  priceGroup: {
    flex: 1,
  },
  priceLabel: {
    fontSize: 13,
    color: '#6c757d',
    marginBottom: 4,
    textAlign: isDesktop ? 'left' : 'center',
  },
  addToCartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0d6efd',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 8,
    alignSelf: isDesktop ? 'center' : 'stretch',
    minWidth: isDesktop ? 180 : undefined,
  },
  addToCartButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  disabledButton: {
    backgroundColor: '#ced4da',
  },
  emptyText: {
    textAlign: 'center',
    marginTop: 48,
    fontSize: 16,
    color: '#6c757d',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: isDesktop ? 32 : 16,
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingVertical: isDesktop ? 28 : 22,
    paddingHorizontal: isDesktop ? 32 : 20,
    width: isDesktop ? '60%' : '90%',
    maxWidth: 540,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#212529',
    textAlign: 'center',
    marginBottom: 20,
  },
  modalProductInfo: {
    flexDirection: isDesktop ? 'row' : 'column',
    alignItems: isDesktop ? 'center' : 'flex-start',
    marginBottom: 18,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
    gap: isDesktop ? 16 : 12,
  },
  modalProductImage: {
    width: isDesktop ? 88 : 72,
    height: isDesktop ? 88 : 72,
    borderRadius: 12,
    backgroundColor: '#f1f3f5',
  },
  modalProductDetails: {
    flex: 1,
  },
  modalProductName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 4,
  },
  modalProductPrice: {
    fontSize: 14,
    color: '#198754',
    fontWeight: '600',
    marginBottom: 4,
  },
  modalProductStock: {
    fontSize: 13,
    color: '#6c757d',
  },
  quantitySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 18,
  },
  quantityButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#f8f9fa',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#dee2e6',
  },
  quantityText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#212529',
    minWidth: 36,
    textAlign: 'center',
  },
  totalText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#198754',
    textAlign: 'center',
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: isDesktop ? 'row' : 'column',
    gap: 12,
  },
  modalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 8,
  },
  cancelButton: {
    backgroundColor: '#6c757d',
  },
  confirmButton: {
    backgroundColor: '#198754',
  },
  cancelButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
  },
  confirmButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
  },
});
