const IP_DA_SUA_MAQUINA = 'localhost';
const LOCATION_SERVICE_PORT = '3001';
const PRODUCT_SERVICE_PORT = '3000';
const PERSON_SERVICE_PORT = '3002';

const LOCATION_API_URL = `http://${IP_DA_SUA_MAQUINA}:${LOCATION_SERVICE_PORT}/api/location`;
const PRODUCT_API_URL = `http://${IP_DA_SUA_MAQUINA}:${PRODUCT_SERVICE_PORT}/api/product`; // <<< Esta URL é usada
const PERSON_API_URL = `http://${IP_DA_SUA_MAQUINA}:${PERSON_SERVICE_PORT}/api`;

export { LOCATION_API_URL, PRODUCT_API_URL, PERSON_API_URL };