import { StyleSheet } from "react-native"

export const productListStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f1f3f5",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e9ecef",
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: "#212529",
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    color: "#868e96",
  },
  addButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0d6efd",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
  },
  scrollArea: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 32,
  },
  filtersCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#dee2e6",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#212529",
    paddingVertical: 8,
  },
  filtersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 16,
    marginHorizontal: -8,
  },
  filterBlock: {
    flexGrow: 1,
    flexBasis: 160,
    minWidth: 140,
    marginHorizontal: 8,
    marginTop: 12,
  },
  filterBlockWide: {
    flexGrow: 2,
    minWidth: 220,
    marginHorizontal: 8,
    marginTop: 12,
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#495057",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  filterPicker: {
    borderWidth: 1,
    borderColor: "#dee2e6",
    borderRadius: 10,
    backgroundColor: "#f8f9fa",
    height: 48,
  },
  clearFiltersButton: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  clearFiltersText: {
    marginLeft: 6,
    fontWeight: "600",
    color: "#495057",
  },
  searchingBadge: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#e7f1ff",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  searchingText: {
    marginLeft: 8,
    color: "#0d6efd",
    fontWeight: "600",
    fontSize: 12,
  },
  tableCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingBottom: 12,
    marginTop: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    position: "relative",
  },
  errorState: {
    padding: 32,
    alignItems: "center",
  },
  errorTitle: {
    marginTop: 12,
    fontSize: 18,
    fontWeight: "700",
    color: "#212529",
    textAlign: "center",
  },
  errorSubtitle: {
    marginTop: 8,
    fontSize: 14,
    color: "#868e96",
    textAlign: "center",
  },
  retryButton: {
    marginTop: 16,
    backgroundColor: "#0d6efd",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
  },
  retryButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  tableFooter: {
    marginTop: 16,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paginationLabel: {
    color: "#495057",
    fontSize: 13,
  },
  paginationControls: {
    flexDirection: "row",
    alignItems: "center",
  },
  pageButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#0d6efd",
    alignItems: "center",
    justifyContent: "center",
  },
  pageButtonDisabled: {
    backgroundColor: "#a5c1f2",
  },
  pageIndicator: {
    marginHorizontal: 12,
    fontSize: 14,
    fontWeight: "600",
    color: "#212529",
  },
  tableOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 12,
  },
  overlayText: {
    marginTop: 8,
    color: "#495057",
    fontWeight: "600",
  },
})